### ISSUE TITLE
Nostr + IPNS Service Bots

### ISSUE THREAD

**Issue by 0xc0de4c0ffee** [namesys-eth/ccip2-eth-backend#1]
~~Some future-istic integration~~

Nostr Bot (A) as service with few public & private nostr gateways to repost all valid IPNS records update received by IPNS republishing service backend.

Nostr Bot (B) as cloud/local/in-browser service to store, update & republish everything based on those Nostr posts from republishing service to speed up initial global propagation time and to republish everything "randomly" from their local DB ~24/7.

As we're already aware of long delays between IPNS updates in public gateway and everything goes down if all republishing services go down for few hrs/>24 hrs time. For now we're ok with 10-20 minutes update time, & have to remove some big public IPFS gateways failing forever to catchup with latest updates, with basic fix *.ipfs2.eth.limo gateway hijacking dear @eth-limo service 😆 to act like IPFS/IPNS gateway to speed up that IPNS updates for ENS.

We'll need Nostr+X bots/services to build everything soon 🌕
Nostr+IPNS Service bots will be huge milestone bridging 2 giant public-open protocols, it'll be fun-easy to learn and buidl this without heavy EVM/contracts and market APIs/stack.. Hope we'll get there soon🖖

**Comment by sshmatrix** [comment]
We will get there. Soon 🚀

**Comment by 0xc0de4c0ffee** [comment]
Roads not taken..
